# Server configuration
server.port=8080

# Production-safe connection string properties
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/vaultbank_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:your_secure_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configurations
app.jwt.secret=${JWT_SECRET_KEY}
app.jwt.expiration-ms=${JWT_EXPIRATION:86400000}
app.interest.cron=${INTEREST_CRON:0 0 0 * * *}
