# Server configuration
server.port=8080

# Production-safe connection string properties
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/vaultbank_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:your_secure_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configurations
app.jwt.secret=${JWT_SECRET_KEY:9a3f94672e412e873a436d41872a4f61c3c97e937d2f44621c107122cf233e382d54e427cf39572c8362df5638294a4c172d8cf4e82b3d}
app.jwt.expiration-ms=${JWT_EXPIRATION:86400000}